### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lucas-android** [UselessHub/Fake-Discord-BloxLink-Bot#1]
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    client = commands.Bot(command_prefix='!')
TypeError: __init__() missing 1 required keyword-only argument: 'intents'

**Comment by johnnyyyyd** [comment]
> Traceback (most recent call last):
> File "main.py", line 9, in
> client = commands.Bot(command_prefix='!')
> TypeError: **init**() missing 1 required keyword-only argument: 'intents'

Did you find out how to fix?

**Comment by UselessHub** [comment]
Yes I know how to fix it. I will update it in a few hours as I will make
the code way more advanced.
